apiVersion: maistra.io/v2
kind: ServiceMeshControlPlane
metadata:
  name: minimal
spec:
  runtime:
    defaults:
      container:
        imageRegistry: de.icr.io/daroczi
        imageTag: 2.1.0
    components:
      pilot:
        container:
          imageName: maistra-istio-pilot
  istio:
    global:
      imagePullSecrets:
      - all-icr-io
  #istio:
    #pilot:
      #image: de.icr.io/daroczi:2.1.0
  #istio:
    #global:
      #hub: de.icr.io/daroczi
  tracing:
    # change to Jaeger to enable tracing
    type: None
  addons:
    jaeger:
      name: jaeger
      install: {}
    grafana:
      enabled: false
      install: {}
    kiali:
      name: kiali
      enabled: false
      install: {}

---

apiVersion: maistra.io/v1
kind: ServiceMeshMemberRoll
metadata:
  name: default
spec:
  members:
  # a list of namespaces that should be joined into the service mesh
  # for example, to add the bookinfo namespace
  #- bookinfo