apiVersion: maistra.io/v2
kind: ServiceMeshControlPlane
metadata:
  name: minimal
spec:
  profiles:
    - "external"
  version: v2.1

  gateways:
     enabled: true
     ingress:
       enabled: true
       ingress: true
       service:
         type: LoadBalancer

  general:
    logging:
      componentLevels:
        default: debug

  techPreview:
    global:
      configValidation: false
      operatorManageWebhooks: true

---

apiVersion: maistra.io/v1
kind: ServiceMeshMemberRoll
metadata:
  name: default
spec:
  members:
  #- hello
  # a list of namespaces that should be joined into the service mesh
  # for example, to add the bookinfo namespace
  #- bookinfo
