apiVersion: maistra.io/v2
kind: ServiceMeshControlPlane
metadata:
  name: excp
spec:
  version: v2.1
  runtime:
    defaults:
      container:
        imageRegistry: smesh21
        imageTag: 2.1.0
  gateways:
     enabled: false
     ingress:
       enabled: false
       ingress: false
     egress:
       enabled: false
     openshiftRoute:
       enabled: false
  general:
    logging:
      componentLevels:
        default: warn
  istio_cni:
    repair:
      enabled: false

  proxy:
    injection:
      autoInject: false
    networking:
      protocol:
        autoDetect:
          inbound: false
          outbound: false
      dns:
        refreshRate: 300s

  security:
    enabled: false
    identity:
      type: Kubernetes

  telemetry:
    enabled: false
    type: Istiod

  policy:
    enabled: false
    type: None

  tracing:
    type: None

  addons:
    prometheus:
      enabled: false
      install:
        service:
          metadata:
            annotations:
              service.alpha.openshift.io/serving-cert-secret-name: prometheus-tls
          ingress:
            enabled: false

    jaeger:
      name: jaeger
      install:
        storage:
          type: Memory
        ingress:
          enabled: false

    grafana:
      enabled: false
      install:
        service:
          metadata:
            annotations:
              service.alpha.openshift.io/serving-cert-secret-name: grafana-tls
          ingress:
            enabled: false
    kiali:
      enabled: false
      name: kiali
      install:
        dashboard:
          viewOnly: false
        service:
          ingress:
            enabled: false
  techPreview:
    meshConfig:
      rootNamespace: external-istiod
      defaultConfig:
        discoveryAddress: external-opneshift-72287d3323ba21ca6bea483947a1068a-0002.eu-de.containers.appdomain.cloud:15443
        proxyMetadata:
          XDS_ROOT_CA: /etc/ssl/certs/ca-certificates.crt
          CA_ROOT_CA: /etc/ssl/certs/ca-certificates.crt
    global:
      caAddress: external-opneshift-72287d3323ba21ca6bea483947a1068a-0002.eu-de.containers.appdomain.cloud:15443
      istioNamespace: external-istiod
      meshID: mesh1
      multiCluster:
        clusterName: remote
      configValidation: false
      operatorManageWebhooks: true
    sidecarInjectorWebhook:
      injectedAnnotations:
        k8s.v1.cni.cncf.io/networks: "istio-cni"
    istio_cni:
      enabled: true
    pilot:
      env:
        INJECTION_WEBHOOK_CONFIG_NAME: ""
        VALIDATION_WEBHOOK_CONFIG_NAME: ""
