apiVersion: maistra.io/v2
kind: ServiceMeshControlPlane
metadata:
  name: excp
  namespace: external-istiod
spec:
  profiles:
    - "external"
  version: v2.1

  general:
    logging:
      componentLevels:
        default: debug

  techPreview:
    meshConfig:
      rootNamespace: external-istiod
      defaultConfig:
        discoveryAddress: external-opneshift-72287d3323ba21ca6bea483947a1068a-0002.eu-de.containers.appdomain.cloud:15443
        proxyMetadata:
          XDS_ROOT_CA: /etc/ssl/certs/ca-certificates.crt
          CA_ROOT_CA: /etc/ssl/certs/ca-certificates.crt
    global:
      caAddress: external-opneshift-72287d3323ba21ca6bea483947a1068a-0002.eu-de.containers.appdomain.cloud:15443
      istioNamespace: external-istiod
      meshID: mesh1
      multiCluster:
        clusterName: remote
      configValidation: false
      operatorManageWebhooks: true
    sidecarInjectorWebhook:
      injectedAnnotations:
        k8s.v1.cni.cncf.io/networks: "istio-cni"
    istio_cni:
      enabled: true
    pilot:
      env:
        INJECTION_WEBHOOK_CONFIG_NAME: ""
        VALIDATION_WEBHOOK_CONFIG_NAME: ""
