apiVersion: maistra.io/v2
kind: ServiceMeshControlPlane
metadata:
  name: minimal
spec:
  version: v2.1
  runtime:
    defaults:
      container:
        imageRegistry: smesh21
        imageTag: 2.1.0
  gateways:
     enabled: false
     ingress:
       enabled: false
       ingress: false
     egress:
       enabled: false
     openshiftRoute:
       enabled: false
  general:
    logging:
      componentLevels:
        default: warn
  istio_cni:
    repair:
      enabled: false

  proxy:
    injection:
      autoInject: false
    networking:
      protocol:
        autoDetect:
          inbound: false
          outbound: false
      dns:
        refreshRate: 300s

  security:
    enabled: false
    identity:
      type: Kubernetes

  telemetry:
    enabled: false
    type: Istiod

  policy:
    enabled: false
    type: None

  tracing:
    type: None

  addons:
    prometheus:
      enabled: false
      install:
        service:
          metadata:
            annotations:
              service.alpha.openshift.io/serving-cert-secret-name: prometheus-tls
          ingress:
            enabled: false

    jaeger:
      name: jaeger
      install:
        storage:
          type: Memory
        ingress:
          enabled: false

    grafana:
      enabled: false
      install:
        service:
          metadata:
            annotations:
              service.alpha.openshift.io/serving-cert-secret-name: grafana-tls
          ingress:
            enabled: false
    kiali:
      enabled: false
      name: kiali
      install:
        dashboard:
          viewOnly: false
        service:
          ingress:
            enabled: false
  techPreview:
    meshConfig:
      rootNamespace: external-istiod
      defaultConfig:
        discoveryAddress: external-opneshift-72287d3323ba21ca6bea483947a1068a-0001.eu-de.containers.appdomain.cloud:15012
        proxyMetadata:
          XDS_ROOT_CA: /etc/ssl/certs/ca-bundle.crt
          CA_ROOT_CA: /etc/ssl/certs/ca-bundle.crt
    global:
      caAddress: external-opneshift-72287d3323ba21ca6bea483947a1068a-0001.eu-de.containers.appdomain.cloud:15012
      istioNamespace: external-istiod
      meshID: mesh1
      multiCluster:
        clusterName: maistra-dp
      configValidation: false
      operatorManageWebhooks: true
    wasmExtensions:
      enabled: false
    sidecarInjectorWebhook:
      objectSelector:
        enabled: false

---

apiVersion: maistra.io/v1
kind: ServiceMeshMemberRoll
metadata:
  name: default
spec:
  members:
  #- hello
  # a list of namespaces that should be joined into the service mesh
  # for example, to add the bookinfo namespace
  #- bookinfo
